project:
  type: website
  title: "Julia Workshop, ISCB 2022, Madison"
  execute-dir: project
  output-dir: _site
  render: 
      - index.qmd
      - about.qmd
      - session0-housekeeping.qmd
      - session1-get-started.qmd
      - session2-tables-and-arrow.qmd
      - session4-exercise.qmd
      - session6-conclusions.qmd

website:
  title: "Julia Workshop"
  subtitle: "ISCB 2022, Madison"
  site-url: https://crsl4.github.io/julia-workshop
  repo-url: https://github.com/crsl4/julia-workshop
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/crsl4/julia-workshop

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

date: 2022-07-10
date-format: iso

jupyter: julia-1.8
