project:
  type: website
  title: "Julia Workshop, ISCB 2022, Madison"
  execute-dir: project
  output-dir: docs
  render: 
      - index.qmd
      - about.qmd
      - session1-get-started.qmd
      - session2a-tables-and-arrow.qmd
      - session2b-interval-overlap.qmd
      - session4-exercise.qmd
      - session5-other-tools.qmd
      - session6-conclusions.qmd

website:
  title: "Julia Workshop"
  subtitle: "ISCB 2022, Madison"
  site-url: https://crsl4.github.io/julia-workshop
  repo-url: https://github.com/crsl4/julia-workshop
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/crsl4/julia-workshop
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - session1-get-started.qmd
      - session2a-tables-and-arrow.qmd
      - session2b-interval-overlap.qmd
      - session4-exercise.qmd
      - session5-other-tools.qmd
      - session6-conclusions.qmd
  page-navigation: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple

date: today
date-format: iso

jupyter: julia-1.8
