---
title: "Julia Workshop for Data Science"
author: "Claudia Solis-Lemus and Douglas Bates"
subtitle: "SMLP2022 Madison"
---

Julia has been called the programming language of the 21st century for scientific computing, data science, and machine learning. As a high-level, high-performance, dynamic language, Julia is faster than other scripting languages because of smart design decisions like type-stability through specialization via multiple-dispatch. Julia's code can be efficient and concise, which leads to clear performance gains. In addition, Julia's environments are fully reproducible and it is easy to express object-oriented and functional programming patterns.

This tutorial will provide an introduction to key Data Science tools in Julia such as data management with Arrow.jl and Tables.jl and (Generalized) linear mixed models with GLMM.jl and MixedModels.jl. Unlike widely used R packages, all packages that we will describe are written 100% in Julia thus illustrating the language’s potential to overcome the two-language problem.

This tutorial will appeal to anyone interested in learning more about Julia and some of the existing Julia packages that are already available for Statistics and Data Science. In addition to lectures, participants will engage in hands-on exercises. For example, participants will bring a dataset of their choice along with an existing script written in another language (R or python) that performs certain data analyses. During the tutorial, participants will translate their work to Julia in-order to compare running times and ease of programming.

## Learning Objectives for Tutorial

At the end of the tutorial, participants will be able to:

- Identify the main features that make Julia an attractive language for Data Science
- Set up a Julia environment to run their data analysis
- Efficiently handle datasets (even across different languages) through Tables.jl and Arrow.jl
- Fit (generalized) linear mixed models with MixedModels.jl
- Communicate across languages (Julia, R, python)

Intended audience and level:
The tutorial is intended for any data scientist with experience in R and/or python who is interested in learning the attractive features of Julia for Data Science. No knowledge of Julia is required.

## Notebooks for the course

  - [Session 0: Housekeeping](session0-housekeeping.qmd)
  - [Session 1: Get Started](session1-get-started.qmd)
  - [Session 4: Hands-on exercise](session4-exercise.qmd)
  - [Session 6: Conclusions](session6-conclusions.qmd)
