---
title: "Julia Workshop for Data Science"
author: "Claudia Solis-Lemus and Douglas Bates"
subtitle: "ISMB 2022 Madison"
jupyter: julia-1.8
---

# Welcome

- Welcome to the Julia workshop for Data Science!
- The goal for the workshop is to highlight the main features that make Julia an attractive option for data science programmers
- The workshop is intended for any data scientist with experience in R and/or python who is interested in learning the attractive features of Julia for Data Science. No knowledge of Julia is required.
- Workshop materials in the github repository [julia-workshop](https://github.com/crsl4/julia-workshop)

# Schedule

| Time | Topic | Notes | Presenter |
| :---: | :---: | :---: | :---: |
| 11:00 - 11:45 | Session 1: Getting started with Julia | [Notes](session1-get-started.qmd) | Claudia Solis-Lemus |
| 11:45 - 12:45 | Session 2: Data tools | | Doug Bates |
| 12:45 - 1:00 | Q&A | | |
| 1:00 - 2:00 | Lunch break | | |
| 2:00 - 3:00 | Session 3: Model fitting | | Doug Bates |
| 3:00 - 3:15 | Session 4: Description of hands-on exercise | | |
| 3:15 - 3:30 | Coffee break | | |
| 3:30 - 4:30 | Hands-on exercise | | Sam Ozminkowski and Bella Wu |
| 4:30 - 4:45 | Presentation of selected participants' scripts | | |
| 4:45 - 5:00 | Coffee break | | |
| 5:00 - 5:30 | Session 5: Other important Data Science tools | [Notes](session5-other-tools.qmd) | Claudia Solis-Lemus |
| 5:30 - 6:00 | Session 6: Conclusions and questions | [Notes](session6-conclusions.qmd) | Claudia Solis-Lemus |


# In preparation for the workshop

Participants are required to follow the next steps before the day of the workshop:

1. Git clone the workshop repository: `git clone https://github.com/crsl4/julia-workshop.git`

2. Install Julia. The recommended option is to use [JuliaUp](https://github.com/JuliaLang/juliaup):

- Windows: `winget install julia -s msstore`

- Mac and Linux: `curl -fsSL https://install.julialang.org | sh`

- Homebrew users: `brew install juliaup`

After JuliaUp is installed, you can install different Julia versions with:
```shell
juliaup add release  ## installs release version
juliaup add beta     ## installs beta version
juliaup st           ## status of julia versions installed
juliaup default beta ## making beta version the default
```

3. Choose a dataset along with a script to analyze it written in another language (R or python) as we will spend part of the workshop translating participants' scripts to Julia.